name: Upload to Dataverse
on:
workflow_dispatch:
jobs:
upload:
runs-on: ubuntu-latest
steps:
- name: Upload repository to Dataverse
uses: IQSS/dataverse-uploader@v1.7
with:
DATAVERSE_TOKEN: ${{ secrets.DATAVERSE_TOKEN }}
DATAVERSE_SERVER: https://dataverse.unimi.it
DATAVERSE_DATASET_DOI: doi: doi.org/10.13130/RD_UNIMI/FFJ3FR
